---
---

###!
    Title: Dev Portfolio Template
    Version: 1.1.2
    Last Change: 03/21/17
    Author: Ryan Fitzgerald
    Repo: https://github.com/RyanFitzgerald/devportfolio-template
    Issues: https://github.com/RyanFitzgerald/devportfolio-template/issues

    Description: This file contains all the scripts associated with the single-page
    portfolio website.
###

$().ready ->
# Remove no-js class
  $('html').removeClass 'no-js'
  # Create timeline
  $('#experience-timeline').each ->
    $this = $(this)
    # Store reference to this
    $userContent = $this.children('div')
    # user content
    # Create each timeline block
    $userContent.each ->
      $(this).addClass('vtimeline-content').wrap('<div class="vtimeline-point"><div class="vtimeline-block"></div></div>')
    # Add icons to each block
    $this.find('.vtimeline-point').each ->
      $(this).prepend('<div class="vtimeline-icon"><i class="fa fa-map-marker"></i></div>')
    # Add dates to the timeline if exists
    $this.find('.vtimeline-content').each ->
      date = $(this).data('date')
      if date # Prepend if exists
        $(this).parent().prepend '<span class="vtimeline-date">' + date + '</span>'
  # Open mobile menu
  $('#mobile-menu-open').click ->
    $('header, body').addClass 'active'
      
  # Close mobile menu
  $('#mobile-menu-close').click ->
    $('header, body').removeClass 'active'

# ---
# generated by js2coffee 2.2.0