# Customize page from here
title: Eloshav.com
description: Common links to find Eloshav on! Steam, Twitch, YouTube and Discord!
url: "https://eloshav.com" # the base hostname & protocol for your site
root_path: eloshav.com

medias:
- title: YouTube
  url: "https://www.youtube.com/user/Eloshav?sub_confirmation=1"
  img: "assets/images/youtube.png"

- title: Twitch.tv
  url: "https://www.twitch.tv/eloshav"
  img: "assets/images/twitch.png"

- title: Discord
  url: "https://discord.gg/ecdTCyR"
  img: "assets/images/discord.png"

- title: Steam
  url: "https://steamcommunity.com/id/eloshav"
  img: "assets/images/steam.png"



markdown: kramdown
permalink: pretty
gems:
 - jekyll-coffeescript
sass:
  style: compressed
